// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wJBuokoAWXvJUSMjHC6YFU
// Component: Tb982NOoW7
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: wJBuokoAWXvJUSMjHC6YFU/projectcss
import sty from "./PlasmicProfilePreferences.module.css"; // plasmic-import: Tb982NOoW7/css
import AddIcon from "./icons/PlasmicIcon__Add"; // plasmic-import: rdtpCj4Wii/icon
import Add2Icon from "./icons/PlasmicIcon__Add2"; // plasmic-import: _Wyx2NmI_y/icon

export const PlasmicProfilePreferences__VariantProps = new Array();

export const PlasmicProfilePreferences__ArgProps = new Array();

function PlasmicProfilePreferences__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"figmaPaste"}
            data-plasmic-override={overrides.figmaPaste}
            className={classNames(projectcss.all, sty.figmaPaste)}
          >
            <div
              data-plasmic-name={"rectangle1"}
              data-plasmic-override={overrides.rectangle1}
              className={classNames(projectcss.all, sty.rectangle1)}
            />

            <div
              data-plasmic-name={"maskGroup"}
              data-plasmic-override={overrides.maskGroup}
              className={classNames(projectcss.all, sty.maskGroup)}
            >
              <div
                data-plasmic-name={"n00554A1"}
                data-plasmic-override={overrides.n00554A1}
                className={classNames(projectcss.all, sty.n00554A1)}
              />
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___5Zkpf
              )}
            >
              {"emily\nnelson"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uuCr
              )}
            >
              {"Email"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mcTM
              )}
            >
              {"26"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ki0De
              )}
            >
              {"Age"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vFwZ6
              )}
            >
              {"07973 123 456"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cfSgP
              )}
            >
              {"Phone"}
            </div>

            <div
              data-plasmic-name={"rectangle3"}
              data-plasmic-override={overrides.rectangle3}
              className={classNames(projectcss.all, sty.rectangle3)}
            />

            <div
              data-plasmic-name={"rectangle4"}
              data-plasmic-override={overrides.rectangle4}
              className={classNames(projectcss.all, sty.rectangle4)}
            />

            <div
              data-plasmic-name={"prefs"}
              data-plasmic-override={overrides.prefs}
              className={classNames(projectcss.all, sty.prefs)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cdyYw
                )}
              >
                {"PREFS"}
              </div>
            </div>

            <div
              data-plasmic-name={"orders"}
              data-plasmic-override={overrides.orders}
              className={classNames(projectcss.all, sty.orders)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__n9S5
                )}
              >
                {"ORDERS"}
              </div>
            </div>

            <div
              data-plasmic-name={"spend"}
              data-plasmic-override={overrides.spend}
              className={classNames(projectcss.all, sty.spend)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__a4IQ
                )}
              >
                {"SPEND"}
              </div>
            </div>

            <div
              data-plasmic-name={"lists"}
              data-plasmic-override={overrides.lists}
              className={classNames(projectcss.all, sty.lists)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zfhB8
                )}
              >
                {"LISTS"}
              </div>
            </div>

            <div
              data-plasmic-name={"group10"}
              data-plasmic-override={overrides.group10}
              className={classNames(projectcss.all, sty.group10)}
            >
              <div
                data-plasmic-name={"group8"}
                data-plasmic-override={overrides.group8}
                className={classNames(projectcss.all, sty.group8)}
              >
                <div
                  data-plasmic-name={"rectangle5"}
                  data-plasmic-override={overrides.rectangle5}
                  className={classNames(projectcss.all, sty.rectangle5)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__w81Lt
                  )}
                >
                  {"Medium"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__timxu
                  )}
                >
                  {"Preferred Size"}
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"group11"}
              data-plasmic-override={overrides.group11}
              className={classNames(projectcss.all, sty.group11)}
            >
              <div
                data-plasmic-name={"group9"}
                data-plasmic-override={overrides.group9}
                className={classNames(projectcss.all, sty.group9)}
              >
                <div
                  data-plasmic-name={"rectangle6"}
                  data-plasmic-override={overrides.rectangle6}
                  className={classNames(projectcss.all, sty.rectangle6)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ufboj
                  )}
                >
                  {"Red"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gUmPl
                  )}
                >
                  {"Preferred COLOUR"}
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"recommended"}
              data-plasmic-override={overrides.recommended}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.recommended
              )}
            >
              {"Recommended "}
            </div>

            <div
              data-plasmic-name={"group1171274658"}
              data-plasmic-override={overrides.group1171274658}
              className={classNames(projectcss.all, sty.group1171274658)}
            >
              <div
                data-plasmic-name={"rectangle39507"}
                data-plasmic-override={overrides.rectangle39507}
                className={classNames(projectcss.all, sty.rectangle39507)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame1171274780"}
                data-plasmic-override={overrides.frame1171274780}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1171274780)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__fJXd)}>
                  <div
                    data-plasmic-name={"vuesaxlinearadd"}
                    data-plasmic-override={overrides.vuesaxlinearadd}
                    className={classNames(projectcss.all, sty.vuesaxlinearadd)}
                  >
                    <AddIcon
                      className={classNames(projectcss.all, sty.svg__ttP3I)}
                      role={"img"}
                    />
                  </div>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame1171274809"}
                data-plasmic-override={overrides.frame1171274809}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1171274809)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__azwtK
                  )}
                >
                  {"Beige Dress"}
                </div>

                <div
                  data-plasmic-name={"group37338"}
                  data-plasmic-override={overrides.group37338}
                  className={classNames(projectcss.all, sty.group37338)}
                >
                  <div
                    data-plasmic-name={"rectangle39506"}
                    data-plasmic-override={overrides.rectangle39506}
                    className={classNames(projectcss.all, sty.rectangle39506)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bVyUn
                    )}
                  >
                    {"$40.00"}
                  </div>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame1171274753"}
                data-plasmic-override={overrides.frame1171274753}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1171274753)}
              >
                <div
                  data-plasmic-name={"vuesaxlinearadd2"}
                  data-plasmic-override={overrides.vuesaxlinearadd2}
                  className={classNames(projectcss.all, sty.vuesaxlinearadd2)}
                >
                  <Add2Icon
                    className={classNames(projectcss.all, sty.svg__rFCjn)}
                    role={"img"}
                  />
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pocdR
                  )}
                >
                  {"0"}
                </div>

                <div
                  data-plasmic-name={"vuesaxlinearadd3"}
                  data-plasmic-override={overrides.vuesaxlinearadd3}
                  className={classNames(projectcss.all, sty.vuesaxlinearadd3)}
                >
                  <AddIcon
                    className={classNames(projectcss.all, sty.svg__b5WmR)}
                    role={"img"}
                  />
                </div>
              </p.Stack>
            </div>

            <div
              data-plasmic-name={"group1171274659"}
              data-plasmic-override={overrides.group1171274659}
              className={classNames(projectcss.all, sty.group1171274659)}
            >
              <div
                data-plasmic-name={"rectangle39508"}
                data-plasmic-override={overrides.rectangle39508}
                className={classNames(projectcss.all, sty.rectangle39508)}
              />

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame1171274781"}
                data-plasmic-override={overrides.frame1171274781}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1171274781)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__v7Ylg)}>
                  <div
                    data-plasmic-name={"vuesaxlinearadd4"}
                    data-plasmic-override={overrides.vuesaxlinearadd4}
                    className={classNames(projectcss.all, sty.vuesaxlinearadd4)}
                  >
                    <AddIcon
                      className={classNames(projectcss.all, sty.svg__vBk6D)}
                      role={"img"}
                    />
                  </div>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame1171274810"}
                data-plasmic-override={overrides.frame1171274810}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1171274810)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wRfJe
                  )}
                >
                  {"Black Jacket"}
                </div>

                <div
                  data-plasmic-name={"group37339"}
                  data-plasmic-override={overrides.group37339}
                  className={classNames(projectcss.all, sty.group37339)}
                >
                  <div
                    data-plasmic-name={"rectangle39509"}
                    data-plasmic-override={overrides.rectangle39509}
                    className={classNames(projectcss.all, sty.rectangle39509)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__o5Q6R
                    )}
                  >
                    {"$50.00"}
                  </div>
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                data-plasmic-name={"frame1171274754"}
                data-plasmic-override={overrides.frame1171274754}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1171274754)}
              >
                <div
                  data-plasmic-name={"vuesaxlinearadd5"}
                  data-plasmic-override={overrides.vuesaxlinearadd5}
                  className={classNames(projectcss.all, sty.vuesaxlinearadd5)}
                >
                  <Add2Icon
                    className={classNames(projectcss.all, sty.svg__dEQwE)}
                    role={"img"}
                  />
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qIgVg
                  )}
                >
                  {"0"}
                </div>

                <div
                  data-plasmic-name={"vuesaxlinearadd6"}
                  data-plasmic-override={overrides.vuesaxlinearadd6}
                  className={classNames(projectcss.all, sty.vuesaxlinearadd6)}
                >
                  <AddIcon
                    className={classNames(projectcss.all, sty.svg__tdl6Y)}
                    role={"img"}
                  />
                </div>
              </p.Stack>
            </div>

            <div
              data-plasmic-name={"group1171274669"}
              data-plasmic-override={overrides.group1171274669}
              className={classNames(projectcss.all, sty.group1171274669)}
            >
              <div
                data-plasmic-name={"rectangle39816"}
                data-plasmic-override={overrides.rectangle39816}
                className={classNames(projectcss.all, sty.rectangle39816)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ss2Go
                )}
              >
                {"S"}
              </div>
            </div>

            <div
              data-plasmic-name={"group1171274670"}
              data-plasmic-override={overrides.group1171274670}
              className={classNames(projectcss.all, sty.group1171274670)}
            >
              <div
                data-plasmic-name={"rectangle39817"}
                data-plasmic-override={overrides.rectangle39817}
                className={classNames(projectcss.all, sty.rectangle39817)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sumSl
                )}
              >
                {"XL"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vXc1
              )}
            >
              {"emily.n@hotmail.com"}
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame1171274740"}
              data-plasmic-override={overrides.frame1171274740}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame1171274740)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rFeg9
                )}
              >
                {"Explore Categories"}
              </div>
            </p.Stack>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "figmaPaste",
    "rectangle1",
    "maskGroup",
    "n00554A1",
    "rectangle3",
    "rectangle4",
    "prefs",
    "orders",
    "spend",
    "lists",
    "group10",
    "group8",
    "rectangle5",
    "group11",
    "group9",
    "rectangle6",
    "recommended",
    "group1171274658",
    "rectangle39507",
    "frame1171274780",
    "vuesaxlinearadd",
    "frame1171274809",
    "group37338",
    "rectangle39506",
    "frame1171274753",
    "vuesaxlinearadd2",
    "vuesaxlinearadd3",
    "group1171274659",
    "rectangle39508",
    "frame1171274781",
    "vuesaxlinearadd4",
    "frame1171274810",
    "group37339",
    "rectangle39509",
    "frame1171274754",
    "vuesaxlinearadd5",
    "vuesaxlinearadd6",
    "group1171274669",
    "rectangle39816",
    "group1171274670",
    "rectangle39817",
    "frame1171274740"
  ],

  figmaPaste: [
    "figmaPaste",
    "rectangle1",
    "maskGroup",
    "n00554A1",
    "rectangle3",
    "rectangle4",
    "prefs",
    "orders",
    "spend",
    "lists",
    "group10",
    "group8",
    "rectangle5",
    "group11",
    "group9",
    "rectangle6",
    "recommended",
    "group1171274658",
    "rectangle39507",
    "frame1171274780",
    "vuesaxlinearadd",
    "frame1171274809",
    "group37338",
    "rectangle39506",
    "frame1171274753",
    "vuesaxlinearadd2",
    "vuesaxlinearadd3",
    "group1171274659",
    "rectangle39508",
    "frame1171274781",
    "vuesaxlinearadd4",
    "frame1171274810",
    "group37339",
    "rectangle39509",
    "frame1171274754",
    "vuesaxlinearadd5",
    "vuesaxlinearadd6",
    "group1171274669",
    "rectangle39816",
    "group1171274670",
    "rectangle39817",
    "frame1171274740"
  ],

  rectangle1: ["rectangle1"],
  maskGroup: ["maskGroup", "n00554A1"],
  n00554A1: ["n00554A1"],
  rectangle3: ["rectangle3"],
  rectangle4: ["rectangle4"],
  prefs: ["prefs"],
  orders: ["orders"],
  spend: ["spend"],
  lists: ["lists"],
  group10: ["group10", "group8", "rectangle5"],
  group8: ["group8", "rectangle5"],
  rectangle5: ["rectangle5"],
  group11: ["group11", "group9", "rectangle6"],
  group9: ["group9", "rectangle6"],
  rectangle6: ["rectangle6"],
  recommended: ["recommended"],
  group1171274658: [
    "group1171274658",
    "rectangle39507",
    "frame1171274780",
    "vuesaxlinearadd",
    "frame1171274809",
    "group37338",
    "rectangle39506",
    "frame1171274753",
    "vuesaxlinearadd2",
    "vuesaxlinearadd3"
  ],

  rectangle39507: ["rectangle39507"],
  frame1171274780: ["frame1171274780", "vuesaxlinearadd"],
  vuesaxlinearadd: ["vuesaxlinearadd"],
  frame1171274809: ["frame1171274809", "group37338", "rectangle39506"],
  group37338: ["group37338", "rectangle39506"],
  rectangle39506: ["rectangle39506"],
  frame1171274753: ["frame1171274753", "vuesaxlinearadd2", "vuesaxlinearadd3"],
  vuesaxlinearadd2: ["vuesaxlinearadd2"],
  vuesaxlinearadd3: ["vuesaxlinearadd3"],
  group1171274659: [
    "group1171274659",
    "rectangle39508",
    "frame1171274781",
    "vuesaxlinearadd4",
    "frame1171274810",
    "group37339",
    "rectangle39509",
    "frame1171274754",
    "vuesaxlinearadd5",
    "vuesaxlinearadd6"
  ],

  rectangle39508: ["rectangle39508"],
  frame1171274781: ["frame1171274781", "vuesaxlinearadd4"],
  vuesaxlinearadd4: ["vuesaxlinearadd4"],
  frame1171274810: ["frame1171274810", "group37339", "rectangle39509"],
  group37339: ["group37339", "rectangle39509"],
  rectangle39509: ["rectangle39509"],
  frame1171274754: ["frame1171274754", "vuesaxlinearadd5", "vuesaxlinearadd6"],
  vuesaxlinearadd5: ["vuesaxlinearadd5"],
  vuesaxlinearadd6: ["vuesaxlinearadd6"],
  group1171274669: ["group1171274669", "rectangle39816"],
  rectangle39816: ["rectangle39816"],
  group1171274670: ["group1171274670", "rectangle39817"],
  rectangle39817: ["rectangle39817"],
  frame1171274740: ["frame1171274740"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProfilePreferences__ArgProps,
          internalVariantPropNames: PlasmicProfilePreferences__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicProfilePreferences__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProfilePreferences";
  } else {
    func.displayName = `PlasmicProfilePreferences.${nodeName}`;
  }
  return func;
}

export const PlasmicProfilePreferences = Object.assign(
  // Top-level PlasmicProfilePreferences renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    figmaPaste: makeNodeComponent("figmaPaste"),
    rectangle1: makeNodeComponent("rectangle1"),
    maskGroup: makeNodeComponent("maskGroup"),
    n00554A1: makeNodeComponent("n00554A1"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle4: makeNodeComponent("rectangle4"),
    prefs: makeNodeComponent("prefs"),
    orders: makeNodeComponent("orders"),
    spend: makeNodeComponent("spend"),
    lists: makeNodeComponent("lists"),
    group10: makeNodeComponent("group10"),
    group8: makeNodeComponent("group8"),
    rectangle5: makeNodeComponent("rectangle5"),
    group11: makeNodeComponent("group11"),
    group9: makeNodeComponent("group9"),
    rectangle6: makeNodeComponent("rectangle6"),
    recommended: makeNodeComponent("recommended"),
    group1171274658: makeNodeComponent("group1171274658"),
    rectangle39507: makeNodeComponent("rectangle39507"),
    frame1171274780: makeNodeComponent("frame1171274780"),
    vuesaxlinearadd: makeNodeComponent("vuesaxlinearadd"),
    frame1171274809: makeNodeComponent("frame1171274809"),
    group37338: makeNodeComponent("group37338"),
    rectangle39506: makeNodeComponent("rectangle39506"),
    frame1171274753: makeNodeComponent("frame1171274753"),
    vuesaxlinearadd2: makeNodeComponent("vuesaxlinearadd2"),
    vuesaxlinearadd3: makeNodeComponent("vuesaxlinearadd3"),
    group1171274659: makeNodeComponent("group1171274659"),
    rectangle39508: makeNodeComponent("rectangle39508"),
    frame1171274781: makeNodeComponent("frame1171274781"),
    vuesaxlinearadd4: makeNodeComponent("vuesaxlinearadd4"),
    frame1171274810: makeNodeComponent("frame1171274810"),
    group37339: makeNodeComponent("group37339"),
    rectangle39509: makeNodeComponent("rectangle39509"),
    frame1171274754: makeNodeComponent("frame1171274754"),
    vuesaxlinearadd5: makeNodeComponent("vuesaxlinearadd5"),
    vuesaxlinearadd6: makeNodeComponent("vuesaxlinearadd6"),
    group1171274669: makeNodeComponent("group1171274669"),
    rectangle39816: makeNodeComponent("rectangle39816"),
    group1171274670: makeNodeComponent("group1171274670"),
    rectangle39817: makeNodeComponent("rectangle39817"),
    frame1171274740: makeNodeComponent("frame1171274740"),
    // Metadata about props expected for PlasmicProfilePreferences
    internalVariantProps: PlasmicProfilePreferences__VariantProps,
    internalArgProps: PlasmicProfilePreferences__ArgProps
  }
);

export default PlasmicProfilePreferences;
/* prettier-ignore-end */
